version: '3.8'
services:
  jmeter:
    build: .
    image: local/jmeter:5.6.3
    working_dir: /tests
    volumes:
      - ../jmeter/plans:/tests
      - ../jmeter/results:/tests/results
      - ../jmeter/reports:/tests/reports
    command:
      - -n
      - -t
      - /tests/google-loadtest.jmx
      - -l
      - /tests/results/results.jtl
      - -e
      - -o
      - /tests/reports/html-report
      - -q
      - /tests/env/qa.properties
      - -Jusers=10
      - -JrampUp=1
      - -Jloops=1