name: JMeter API Load Test (Docker)

on:
  push:
    branches: [ "qa" ]

jobs:
  api-loadtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build JMeter image
        working-directory: perf/docker
        run: docker compose build jmeter

      - name: Run API Load Test with JMeter
        working-directory: perf/docker
        env:
          ENV_NAME: qa
          USERS: '10'
          RAMP_UP: '1'
          LOOPS: '1'
        run: |
          echo "🚀 Running API Load Test against: https://reqres.in/api/users?page=2"
          docker compose run --rm jmeter \
            -n -t /tests/google-loadtest.jmx \
            -l /tests/results/results.jtl \
            -e -o /tests/reports/html-report \
            -q /tests/env/${ENV_NAME}.properties \
            -Jusers=${USERS} -JrampUp=${RAMP_UP} -Jloops=${LOOPS}

      - name: Upload API Load Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-loadtest-html-report
          path: perf/jmeter/reports/html-report
          if-no-files-found: error
